# Declare variables to be passed into your templates

configurationOverrides:
  global: 
    namespace: confluent
    imageTag: 7.3.0
    initTag: 2.5.0

  kafka:
    replicas: 3
    dataVolumeCapacity: 10G
    serverPropertiesOverride:
      "offsets.topic.replication.factor": 3
      "default.replication.factor": 3
      "min.insync.replicas": 2

  zookeeper:
    replicas: 3
    dataVolumeCapacity: 10Gi
    logVolumeCapacity: 10Gi