apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: {{ .Values.configurationOverrides.global.namespace }}
spec:
  replicas: {{ .Values.configurationOverrides.controlcenter.replicas }}
  image:
    application: confluentinc/cp-enterprise-control-center:{{ .Values.configurationOverrides.global.imageTag }}
    init: confluentinc/confluent-init-container:{{ .Values.configurationOverrides.global.initTag }}
  dataVolumeCapacity: {{ .Values.configurationOverrides.controlcenter.dataVolumeCapacity }}
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
      authentication:
        type: mtls
      tls:
        enabled: true
    ksqldb:
      - name: ksqldb
        url: http://ksqldb.confluent.svc.cluster.local:8088
        authentication:
          type: mtls
        tls:
          enabled: true        
    connect:
      - name: connect
        url: http://connect.confluent.svc.cluster.local:8083
        authentication:
         type: mtls
        tls:
          enabled: true
  tls:
    autoGeneratedCerts: true
